'use client';

import type { PublicItem } from '@/domain/iq/bank';

/**
 * The question's stimulus: a sentence, a figure, or nothing.
 *
 * SVG is injected as markup because the figures ARE markup — they were
 * generated by us, ship inside the bundle, and never come from a person. A
 * check in `bank.test.ts` asserts none of them carries a script, an event
 * handler, or an external reference, so the trust here rests on a test rather
 * than on the claim that the data is ours.
 *
 * The figure sits in a square box with a white ground, because the art is
 * black line work drawn for paper. Dropping it straight onto the near-black
 * page would render it invisible.
 */
export function Stimulus({ item }: { item: PublicItem }) {
  if (item.formato_estimulo === 'none' || !item.estimulo) return null;

  if (item.formato_estimulo === 'svg') {
    return (
      <div
        className="iq-figure iq-figure-stimulus"
        role="img"
        aria-label={item.enunciado}
        dangerouslySetInnerHTML={{ __html: item.estimulo }}
      />
    );
  }

  // Text stimuli are sequences and analogies — monospaced so the terms line up
  // and a digit is not mistaken for its neighbour.
  return <p className="iq-stimulus-text">{item.estimulo}</p>;
}
